### ISSUE TITLE
Run CRAN compliance check

### ISSUE THREAD

**Issue by mbannert** [NilsPetras/IPV#5]
R CMD CHECK --as-cran 
also run with the rhub package

**Comment by NilsPetras** [comment]
If have done that and eliminated all issues except for:
a) a warning, that i should document my data sets, which i will do later
b) a note that variables are not defined within the plot_* functions, because they are defined in the model_* functions and passed on. I figured I should define the object that is handed on from the model_* functions to the plot_* functions as a class to solve the issue, but I would like to do that later.
c) a note about my non-standard top level directory "examples" which I only really need for the usability check and i will certainly clean up completely by putting all examples in either @examples or the vignette
