### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by NilsPetras** [NilsPetras/IPV#7]
How do I set up examples within the package? More specifically:

1. is it smart to set up the examples now?
2. how does the referencing work within the package? (e.g. between folders like "R" and "examples")
to a) open data files and b) call functions
3. what do I need beyond the @examples code snippits in the roxygen documentation, when providing an example?
4. how do I open my data in the @examples? I have examples that read .RData files and examples that read .xlsx files

**Comment by mbannert** [comment]
ad 1: examples are always a good idea. Yet I think you need to build your package once first in order to understand what packaging does for you and how namespaces work. That would most likely answer all of your questions here. That being said @hadley 's  http://r-pkgs.had.co.nz/ is an excellent and very practical read on how-to-create-an-R-package-the-right-way. 

ad 2: packages have their own namespaces. I.e. no need to source anything. once the package is loaded (the `load_all` function from `devtools` can do that for you while developing) all exported functions can be called without referencing. unexported functions can be called from other functions of the same package. also make sure to understand the `package::function_name()` syntax.

ad 3: nothing

ad 4: put the data into your package's data folder (see @hadley's online book / link) I recommend to not use xlsx because you do not want to depend on a xlsx reading package just because of an example (you could use `suggest` in your description but that's another story). I recommend to create R binary data according to @hadley's guide.

**Comment by NilsPetras** [comment]
I just set up my package in the master branch using RStudio and devtools to generate the package infrastructure. Using @hadley 's instructions i came up with the idea of
1) putting .rda example files in data/
2) putting .xlsx example files in inst/extdata
because i have a combination of two functions that read .xlsx files and need to provide examples for those, including the right setup of the .xlsx files.

Is that a good practical solution?

**Comment by mbannert** [comment]
Kinda. Roughly speaking, yes. Though you could improve on some details: 

- IPV should not be a subfolder of the repository, IPV is the repository itself the additional folder in the master branch makes no sense. It also hampers direct installation via `devtools::install_github`.

- if you choose to keep your excel dependency, this seems reasonable to me. 

- do you aim at merging the dev and master branch again? If so... you'll probably have a hard time as a git beginner to merge branches that diverged so substantially (w.r.t the same files). There's no need to merge the branches, you may very well discard `dev` or simply use it for inspiration. Just sayin' that your approach is not how you typically use branches in git. Yet this doesn't say anything about the package. It's only git gibberish.

**Comment by NilsPetras** [comment]
I will sort out the subfolder thing, good point. And yes, I very much need the excel dependency, because it is much more convenient in its current state than manual input using R.

Regarding branches: The master branch was already behind and ill-constructed to the point of complete uselessness, so i figured setting it up from scratch and using the important elements from the dev branch was much quicker than going through the git commits along the way. I guess the more principle approach would have been to set up a new branch and leave master as is for the time being.

Edit: is there some specific issue I need to look out for regarding package::function_name() instead of function_name()?
